name: 'EB Deployment'
description: 'Elastic Beanstalk workflow deployment'

inputs:
  application:
    description: 'Application name'
    required: true
  country:
    description: 'Country deployment'
    required: true
    default: 'chile'
  environment:
    description: 'Environment deployment'
    required: true
    default: 'development'
  aws-access-key-id:
    description: 'AWS access ID'
    required: true
  aws-secret-access-key:
    description: 'AWS access secret key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: us-east-1
  icon:
    description: 'Country icon'
    required: true


runs:
  using: "composite"
  steps:

    - name: 🇨🇱 Deployment Chile 🇨🇱
      if: inputs.country == 'chile'
      uses: Drakefsi/pj-actions/eb/deploy.yml@master
      with:
        application: ${{ inputs.application }}
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    
