name: 'EB Deployment'
description: 'Elastic Beanstalk workflow deployment'

inputs:
  application:
    description: 'Application name'
    required: true    
  environment:
    description: 'Environment deployment'
    required: true
    default: 'development'
  aws-access-key-id:
    description: 'AWS access ID'
    required: true
  aws-secret-access-key:
    description: 'AWS access secret key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: us-east-1
  icon:
    description: 'Country icon'
    required: true



runs:
    using: "composite"
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy EB
      shell: bash
      run: |
        echo "--- Installing EB CLI ---"
        python -m pip install --upgrade pip
        pip install awsebcli --upgrade
        eb --version
        echo "--- Deploy ---"
        eb use ${{ inputs.application }}-${{ inputs.environment }}
        eb deploy ${{ inputs.application }}-${{ inputs.environment }}
      env:
        DEBIAN_FRONTEND: noninteractive
    
