name: 'EB Deployment'
description: 'Elastic Beanstalk workflow deployment'

inputs:
  application:
    description: 'Application name'
    required: true    
  environment:
    description: 'Environment deployment'
    required: true
    default: 'development'
  aws-access-key-id:
    description: 'AWS access ID'
    required: true
  aws-secret-access-key:
    description: 'AWS access secret key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: us-east-1
  icon:
    description: 'Country icon'
    required: true
  plataform:
    description: 'Environment plataform'
    requied: true
  branch-release:
    description: 'Branch or release to deploy'
    required: true
  slack-bot-token:
    description: 'Slack token'
    required: true
  slack-channel:
    description: 'Slack channel'
    required: true

runs:
    using: "composite"
    steps:

    - name: 🚀 Slack status
      if: ${{ always() }}
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
             "attachments":[
                {
                   "mrkdwn_in": ["text"],
                   "author_name":"Github actions",
                   "author_link":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                   "color":"",
                   "text":"*Deployment:* ${{ inputs.application }} | *tag/release* ${{ inputs.branch-release }} | ${{ inputs.icon }}",
                   "fields":[
                      {
                         "title": "Status",
                         "short":true,
                         "value":"_In Progress_"
                      }
                   ]
                }
             ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}

    - name: 🌧️ Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: ✨ Checkout Code
      uses: actions/checkout@v3

    - name: 🔧  Get tag name
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "RELEASE=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: 🧰 Install eb-cli
      shell: bash
      run: |
        sudo pip config --global set global.index-url http://${PROXY_DOMAIN}:${PROXY_PORT}${PROXY_PATH}
        sudo pip config --global set global.trusted-host ${PROXY_DOMAIN}
        python -m pip install --upgrade pip
        pip install awsebcli --upgrade
      env:
        PROXY_DOMAIN: nexus.nexus.svc.local
        PROXY_PORT: 8081
        PROXY_PATH: /repository/pip-proxy/simple/

    - name: 🛸 Deploy Elastic Beanstalk
      shell: bash
      run: |
        eb --version
        eb init ${{ inputs.application }} --region ${{ inputs.aws-region }} --platform "${{ inputs.plataform }}"
        eb deploy ${{ inputs.application }}-${{ inputs.environment }} -v --process

    - name: 🚀 Slack success ✅
      if: ${{ success() }}
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
             "attachments":[
                {
                   "mrkdwn_in": ["text"],
                   "author_name":"*Deployment:* ${{ inputs.application }}",
                   "author_link":"${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}",
                   "color":"#03fc28",
                   "text":"*release* ${{ env.RELEASE }} | ${{ inputs.icon }}"
                }
             ]
          }
        update-ts: ${{ steps.slack.outputs.ts }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        RELEASE: ${{ env.RELEASE || inputs.branch-release }}

    - name: 🚀 Slack failure ❌
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
             "attachments":[
                {
                   "mrkdwn_in": ["text"],
                   "author_name":"*Deployment:* ${{ inputs.application }}",
                   "author_link":"${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}",
                   "color":"#fc4503",
                   "text":"*release* ${{ env.RELEASE }} | ${{ inputs.icon }}"
                }
             ]
          }
        update-ts: ${{ steps.slack.outputs.ts }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        RELEASE: ${{ env.RELEASE || inputs.branch-release }}

    - name: 🚀 Slack cancelled ⚠️
      if: ${{ cancelled() }}
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
             "attachments":[
                {
                   "mrkdwn_in": ["text"],
                   "author_name":"*Deployment:* ${{ inputs.application }}",
                   "author_link":"${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}",
                   "color":"#fce803",
                   "text":"*release* ${{ env.RELEASE }} | ${{ inputs.icon }}"
                }
             ]
          }
        update-ts: ${{ steps.slack.outputs.ts }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        RELEASE: ${{ env.RELEASE || inputs.branch-release }}
