name: 'EB Deployment'
description: 'Elastic Beanstalk workflow deployment'

inputs:
  application:
    description: 'Application name'
    required: true
  application_name:
    description: 'Alternative application name'
    required: false
  environment:
    description: 'Environment deployment'
    required: true
    default: 'development'
  aws-access-key-id:
    description: 'AWS access ID'
    required: true
  aws-secret-access-key:
    description: 'AWS access secret key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: us-east-1
  icon:
    description: 'Country icon'
    required: true
  plataform:
    description: 'Environment plataform'
    required: true
  branch-release:
    description: 'Branch or release to deploy'
    required: true
  slack-bot-token:
    description: 'Slack token'
    required: true
  slack-channel:
    description: 'Slack channel'
    required: true
  teams-webhook:
    description: 'Teams webhook'
    requierd: false

runs:
    using: "composite"
    steps:

    - name: 🔧  Get tag name
      shell: bash
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "RELEASE=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: 🚀 Slack status
      if: ${{ always() }}
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
             "attachments":[
                {
                   "mrkdwn_in": ["text"],
                   "author_name":"Deployment ${{ inputs.application }}",
                   "author_link":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                   "color":"",
                   "text":"${{ inputs.icon }} *Release* ${{ env.RELEASE }} _by @${{ github.actor }}_"
                }
             ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        RELEASE: ${{ env.RELEASE || inputs.branch-release }}

    - name: 🌧️ Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: ✨ Checkout Code
      uses: actions/checkout@v3

    - name: 🧰 Install eb-cli
      shell: bash
      run: |
        sudo pip config --global set global.index-url http://${PROXY_DOMAIN}:${PROXY_PORT}${PROXY_PATH}
        sudo pip config --global set global.trusted-host ${PROXY_DOMAIN}
        python -m pip install --upgrade pip
        pip install urllib3==1.26.9
        pip install awsebcli --upgrade
      env:
        PROXY_DOMAIN: nexus.nexus.svc.local
        PROXY_PORT: 8081
        PROXY_PATH: /repository/pip-proxy/simple/

    - name: 🛸 Deploy Elastic Beanstalk
      shell: bash
      run: |
        eb --version
        eb init ${{ inputs.application_name || inputs.application }} --region ${{ inputs.aws-region }} --platform "${{ inputs.plataform }}"
        eb deploy ${{ inputs.application }}-${{ inputs.environment }} -v --process

    - name: 🚀 Slack success ✅
      if: ${{ success() }}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
             "attachments":[
                {
                   "mrkdwn_in": ["text"],
                   "author_name":"Deployment ${{ inputs.application }}",
                   "author_link":"${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}",
                   "color":"#03fc28",
                   "text":"${{ inputs.icon }} *Release* ${{ env.RELEASE }} _by @${{ github.actor }}_"
                }
             ]
          }
        update-ts: ${{ steps.slack.outputs.ts }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        RELEASE: ${{ env.RELEASE || inputs.branch-release }}

    - name:  🚀 Teams success ✅
      if: ${{ success() }}
      shell: bash
      run: |
        curl --silent \
        --output /dev/null \
        --header 'content-type: application/json' \
        --url 'https://pjespana.webhook.office.com/webhookb2/65956035-7186-4cf7-b12e-fcc893883b7b@13dfae86-18c7-40da-884d-fee62609a1f4/IncomingWebhook/f23f53332c4046f29f6a57249b229441/47b99226-c1d9-4d79-a1d0-6ca628a41c4f' \
        --data-raw '{  
        "@type": "MessageCard",  
        "@context": "http://schema.org/extensions",  
        "themeColor": "03fc28",  
        "summary": "Rolling Workflow started",  
        "sections": [{  
            "activityTitle": "Rolling Workflow started",  
            "activitySubtitle": "Workflow Notification",  
            "activityImage": "",  
            "facts": [{  
                "name": "URL",  
                "value": "[Rolling Workflow](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }})"
            },  
            {  
                "name": "Application",  
                "value": "[${{ inputs.application }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }})"
            },  
            {  
                "name": "Country",
                "value": "${{ inputs.icon }}"
            },
            {
                "name": "Release",
                "value": "${{ env.RELEASE }}"
            },
            {  
                "name": "Triggered By",  
                "value": "@${{ github.actor }}"
            }],  
            "markdown": true  
          }]  
        }'
      env:
        RELEASE: ${{ env.RELEASE || inputs.branch-release }}

    - name: 🚀 Slack failure ❌
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
             "attachments":[
                {
                   "mrkdwn_in": ["text"],
                   "author_name":"Deployment ${{ inputs.application }}",
                   "author_link":"${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}",
                   "color":"#fc4503",
                   "text":"${{ inputs.icon }} *Release* ${{ env.RELEASE }} _by @${{ github.actor }}_"
                }
             ]
          }
        update-ts: ${{ steps.slack.outputs.ts }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        RELEASE: ${{ env.RELEASE || inputs.branch-release }}

#    - name:  🚀 Teams failure ❌
#      if: ${{ failure() }}
#      uses: aliencube/microsoft-teams-actions@v0.8.0
#      with:
#        webhook_uri: ${{ inputs.teams-webhook }}
#        title: "Deployment ${{ inputs.application }}"
#        summary: "${{ inputs.icon }} *Release* ${{ env.RELEASE }} _by @${{ github.actor }}_"
#        text: "${{ inputs.icon }} *Release* ${{ env.RELEASE }} _by @${{ github.actor }}_"
#        theme_color: fc4503
#        sections: '[{ "activityTitle": "Deployment" }]'
#        actions: '[{ "@type": "OpenUri", "name": "GH actions", "targets": [{"uri": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}" }] }]'

    - name: 🚀 Slack cancelled ⚠️
      if: ${{ cancelled() }}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
             "attachments":[
                {
                   "mrkdwn_in": ["text"],
                   "author_name":"Deployment ${{ inputs.application }}",
                   "author_link":"${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}",
                   "color":"#fce803",
                   "text":"${{ inputs.icon }} *Release* ${{ env.RELEASE }} _by @${{ github.actor }}_"
                }
             ]
          }
        update-ts: ${{ steps.slack.outputs.ts }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        RELEASE: ${{ env.RELEASE || inputs.branch-release }}

#    - name:  🚀 Teams cancelled ⚠️
#      if: ${{ cancelled() }}
#      uses: aliencube/microsoft-teams-actions@v0.8.0
#      with:
#        webhook_uri: ${{ inputs.teams-webhook }}
#        title: "Deployment ${{ inputs.application }}"
#        summary: "${{ inputs.icon }} *Release* ${{ env.RELEASE }} _by @${{ github.actor }}_"
#        text: "${{ inputs.icon }} *Release* ${{ env.RELEASE }} _by @${{ github.actor }}_"
#        theme_color: fc4503
#        sections: '[{ "activityTitle": "Deployment" }]'
#        actions: '[{ "@type": "OpenUri", "name": "GH actions", "targets": [{"uri": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}" }] }]'
