name: 'Terraform Teams message'
description: 'Terraform message to teams'

inputs:
  country:
    description: 'Deployment country'
    required: true
  country-icon:
    description: 'Deployment country icon'
    required: true
  teams-webhook:
    description: 'Teams webhook'
    requierd: true
  teams-message:
    description: 'Teams message'
    required: true


runs:
    using: "composite"
    steps:

    - name:  Teams message success
      shell: bash
      run: |
        curl --silent \
        --output /dev/null \
        --header 'content-type: application/json' \
        --url '${{ inputs.teams-webhook }}' \
        --data-raw '{  
        "@type": "MessageCard",  
        "@context": "http://schema.org/extensions",  
        "themeColor": "03fc28",
        "summary": "${{ inputs.teams-message }}",
        "sections": [{  
            "activityTitle": "${{ inputs.teams-message }}", 
            "facts": [ 
            {  
                "name": "Country",
                "value": "${{ inputs.country-icon }} ${{ inputs.country }}"
            },
            {
                "name": "Repository",
                "value": "${{ github.repository }}"
            },
            {  
                "name": "Triggered By",  
                "value": "@${{ github.actor }}"
            }],  
            "markdown": true  
          }]  
        }'
