name: 'Terraform PR'
description: 'Terraform PR comment status'

inputs:
  github-token:
    description: 'Github TOKEN'
    required: true
  fmt-status: 
    descrition: 'Terraform fmt Status'
    required: true
  init-status:
    descrition: 'Terraform init Status'
    required: true
  plan-status:
    description: 'Terraform plan Status'
    required: true

runs:
    using: "composite"
    steps:

    - name: 🔰 Pull request comments
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require("fs");
          const plan = fs.readFileSync("/tmp/plan.txt", "utf8");
          const maxGitHubBodyCharacters = 65536;

          function chunkSubstr(str, size) {
            const numChunks = Math.ceil(str.length / size)
            const chunks = new Array(numChunks)
            for (let i = 0, o = 0; i < numChunks; ++i, o += size) {
              chunks[i] = str.substr(o, size)
            }
            return chunks
          }

          // Split the Terraform plan into chunks if it's too big and can't fit into the GitHub Action
          var plans = chunkSubstr(plan, maxGitHubBodyCharacters); 
          for (let i = 0; i < plans.length; i++) {
            const output = `### Part # ${i + 1}
            #### Terraform Format and Style 🖌\`${{ inputs.fmt-status }}\`
            #### Terraform Initialization ⚙️\`${{ inputs.init-status }}\`
            #### Terraform Plan 📖\`${{ inputs.plan-status }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${plans[i]}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;   
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }
